### ISSUE TITLE
environment.yml / requirements.txt missing?

### ISSUE THREAD

**Issue by jf---** [compas-ITA19/ITA19#6]
Perhaps an idea to be explicit which dependency versions are expected / to provide a `environment.yml` for the repo? 

Probably going overboard, but PyCharm has pretty nice interface which shows what is the latest version nr for a particular dependency, and conda & pip dont bite 

![image](https://user-images.githubusercontent.com/620988/74434795-6e734b80-4e63-11ea-925d-ae230079fcf2.png)

```yaml
dependencies:
  - python=3.6
  - lxml>=4.2 # redundant, see xml
  - numpy=1.14.0 # 1.15 gives issues
  - yarn
  - pip
  - pip:
    - -r file:requirements.txt # warm fuzzy version completion in IDE

```
